[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
env_logger = "0.10"
log = "0.4.22"
actix-files = "0.6.6"
fs = "0.0.5"
serde_json = "1.0.135"